yarnPath: .yarn/releases/yarn-2.4.0.cjs
packageExtensions:
  # https://github.com/firebase/firebase-js-sdk/issues/3707
  "@firebase/database@*":
    peerDependencies:
      "@firebase/app": "*"
      "@firebase/app-types": "*"